# Generated by Django 6.0.1 on 2026-01-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='S, M, L, XL', max_length=100, verbose_name='Доступные размеры'),
        ),
    ]
