# Generated by Django 6.0.1 on 2026-01-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('completed', 'Выполнен')], default='new', max_length=20),
        ),
    ]
