# Generated by Django 6.0.1 on 2026-01-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='Номер отслеживания'),
        ),
    ]
