# Generated by Django 6.0.1 on 2026-01-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_order_address_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
